teams = {
	'CLE': {
		'location': 'Cleveland',
		'mascot': 'Browns',
		'logo': '../images-nfl/browns.webp',
		'primary': (255, 60, 0),
		'secondary': (49, 29, 0),
	},
	'SEA': {
		'location': 'Seattle',
		'mascot': 'Seahawks',
		'logo': '../images-nfl/seahawks.webp',
		'primary': (0, 0, 0),
		'secondary': (100, 100, 100),
	},
	'LAR': {
		'location': 'Los Angeles',
		'mascot': 'Rams',
		'logo': '../images-nfl/rams.webp',
		'primary': (0, 0, 0),
		'secondary': (100, 100, 100),
	},
	'MIA': {
		'location': 'Miami',
		'mascot': 'Dolphins',
		'logo': '../images-nfl/dolphins.webp',
		'primary': (0, 0, 0),
		'secondary': (100, 100, 100),
	},
	'SF': {
		'location': 'San Francisco',
		'mascot': '49ers',
		'logo': '../images-nfl/49ers.webp',
		'primary': (0, 0, 0),
		'secondary': (100, 100, 100),
	},
	'KC': {
		'location': 'Kansas City',
		'mascot': 'Chiefs',
		'logo': '../images-nfl/chiefs.webp',
		'primary': (0, 0, 0),
		'secondary': (100, 100, 100),
	},
	'CIN': {
		'location': 'Cincinnati',
		'mascot': 'Bengals',
		'logo': '../images-nfl/bengals.webp',
		'primary': (0, 0, 0),
		'secondary': (100, 100, 100),
	},
	'LAC': {
		'location': 'Los Angeles Chargers',
		'mascot': 'Chargers',
		'logo': '../images-nfl/chargers.webp',
		'primary': (0, 0, 0),
		'secondary': (100, 100, 100),
	},
	'LV': {
		'location': 'Las Vegas',
		'mascot': 'Raiders',
		'logo': '../images-nfl/raiders.webp',
		'primary': (0, 0, 0),
		'secondary': (100, 100, 100),
	},
	'PIT': {
		'location': 'Pittsburgh',
		'mascot': 'Steelers',
		'logo': '../images-nfl/steelers.webp',
		'primary': (0, 0, 0),
		'secondary': (100, 100, 100),
	},
	'ATL': {
		'location': 'Atlanta',
		'mascot': 'Falcons',
		'logo': '../images-nfl/falcons.webp',
		'primary': (0, 0, 0),
		'secondary': (100, 100, 100),
	},
	'GB': {
		'location': 'Green Bay',
		'mascot': 'Packers',
		'logo': '../images-nfl/packers.webp',
		'primary': (0, 0, 0),
		'secondary': (100, 100, 100),
	},
	'CHI': {
		'location': 'Chicago',
		'mascot': 'Bears',
		'logo': '../images-nfl/bears.webp',
		'primary': (0, 0, 0),
		'secondary': (100, 100, 100),
	},
	'JAX': {
		'location': 'Jacksonville',
		'mascot': 'Jaguars',
		'logo': '../images-nfl/jaguars.webp',
		'primary': (0, 0, 0),
		'secondary': (100, 100, 100),
	},
	'DET': {
		'location': 'Detroit',
		'mascot': 'Lions',
		'logo': '../images-nfl/lions.webp',
		'primary': (0, 0, 0),
		'secondary': (100, 100, 100),
	},
	'NYJ': {
		'location': 'New York',
		'mascot': 'Jets',
		'logo': '../images-nfl/jets.webp',
		'primary': (0, 0, 0),
		'secondary': (100, 100, 100),
	},
	'MIN': {
		'location': 'Minnesota',
		'mascot': 'Vikings',
		'logo': '../images-nfl/vikings.webp',
		'primary': (0, 0, 0),
		'secondary': (100, 100, 100),
	},
	'WSH': {
		'location': 'Washington',
		'mascot': 'Commanders',
		'logo': '../images-nfl/commanders.webp',
		'primary': (0, 0, 0),
		'secondary': (100, 100, 100),
	},
	'NYG': {
		'location': 'New York',
		'mascot': 'Giants',
		'logo': '../images-nfl/giants.webp',
		'primary': (0, 0, 0),
		'secondary': (100, 100, 100),
	},
	'TEN': {
		'location': 'Tennessee',
		'mascot': 'Titans',
		'logo': '../images-nfl/titans.webp',
		'primary': (0, 0, 0),
		'secondary': (100, 100, 100),
	},
	'PHI': {
		'location': 'Philadelphia',
		'mascot': 'Eagles',
		'logo': '../images-nfl/eagles.webp',
		'primary': (0, 0, 0),
		'secondary': (100, 100, 100),
	},
	'DEN': {
		'location': 'Denver',
		'mascot': 'Broncos',
		'logo': '../images-nfl/broncos.webp',
		'primary': (0, 0, 0),
		'secondary': (100, 100, 100),
	},
	'BAL': {
		'location': 'Baltimore',
		'mascot': 'Ravens',
		'logo': '../images-nfl/ravens.webp',
		'primary': (0, 0, 0),
		'secondary': (100, 100, 100),
	},
	'HOU': {
		'location': 'Houston',
		'mascot': 'Texans',
		'logo': '../images-nfl/texans.webp',
		'primary': (0, 0, 0),
		'secondary': (100, 100, 100),
	},
	'IND': {
		'location': 'Indianapolis',
		'mascot': 'Colts',
		'logo': '../images-nfl/colts.webp',
		'primary': (0, 0, 0),
		'secondary': (100, 100, 100),
	},
	'DAL': {
		'location': 'Dallas',
		'mascot': 'Cowboys',
		'logo': '../images-nfl/cowboys.webp',
		'primary': (0, 0, 0),
		'secondary': (100, 100, 100),
	},
	'BUF': {
		'location': 'Buffalo',
		'mascot': 'Bills',
		'logo': '../images-nfl/bills.webp',
		'primary': (0, 0, 0),
		'secondary': (100, 100, 100),
	},
	'NE': {
		'location': 'New England',
		'mascot': 'Patriots',
		'logo': '../images-nfl/patriots.webp',
		'primary': (0, 0, 0),
		'secondary': (100, 100, 100),
	},
	'NO': {
		'location': 'New Orleans',
		'mascot': 'Saints',
		'logo': '../images-nfl/saints.webp',
		'primary': (0, 0, 0),
		'secondary': (100, 100, 100),
	},
	'TB': {
		'location': 'Tampa Bay',
		'mascot': 'Buccaneers',
		'logo': '../images-nfl/buccaneers.webp',
		'primary': (0, 0, 0),
		'secondary': (100, 100, 100),
	},
}

'''
  'name': 'SEA @ LAR',
  'name': 'MIA @ SF',
  'name': 'KC @ CIN',
  'name': 'LAC @ LV',
  'name': 'PIT @ ATL',
  'name': 'GB @ CHI',
  'name': 'JAX @ DET',
  'name': 'NYJ @ MIN',
  'name': 'WSH @ NYG',
  'name': 'TEN @ PHI',
  'name': 'DEN @ BAL',
  'name': 'CLE @ HOU',
  'name': 'IND @ DAL',
  'name': 'BUF @ NE',
  'name': 'NO @ TB',
'''